### PR TITLE
Task7

### PR DESCRIPTION
**Pull request by loginov-rocks**
- Task: https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task7-lambda%2Bcognito-authorization/task.md
- FE PR: https://github.com/loginov-rocks/nodejs-aws-fe/pull/7
- FE: https://drh6q7egmt2il.cloudfront.net/
- Evaluation criteria:
  - [x] 1 - authorization-service is added to the repo, has correct basicAuthorizer lambda and correct serverless.yaml file
  - [x] 3 - import-service serverless.yaml file has authorizer configuration for the importProductsFile lambda. Request to the importProductsFile lambda should work only with correct authorization_token being decoded and checked by basicAuthorizer lambda. Response should be in 403 HTTP status if access is denied for this user (invalid authorization_token) and in 401 HTTP status if Authorization header is not provided.
  - [x] 5 - update client application to send Authorization: Basic authorization_token header on import. Client should get authorization_token value from browser localStorage https://developer.mozilla.org/ru/docs/Web/API/Window/localStorage authorization_token = localStorage.getItem('authorization_token')
- Additional (optional) tasks:
  - [x] +1 - Client application should display alerts for the responses in 401 and 403 HTTP statuses. This behavior should be added to the nodejs-aws-fe-main/src/index.tsx file

How to test?
- API: https://78s203i22m.execute-api.eu-central-1.amazonaws.com/dev/import?name=test.csv
- Valid credentials:
  - username: `loginov_rocks` (dashes are not supported as env keys)
  - password: `TEST_PASSWORD`
  - `btoa('loginov_rocks:TEST_PASSWORD') = bG9naW5vdl9yb2NrczpURVNUX1BBU1NXT1JE`
- Put `authorization_token = bG9naW5vdl9yb2NrczpURVNUX1BBU1NXT1JE` into the local storage
- Product Service hidden completely behind the Cognito authorizer, use the following button on the front end to sign up and redirect back to the front end with tokens. The front end will automatically pick up tokens and use them along with the requests to the Product Service.
Screen Shot 2020-11-29 at 3 24 31 PM

Architecture:

Architecture

### CODE REVIEW

**Comment by VestryOd** [comment]
image
With using localstorage only 401 status - doesn't work properly.

**Comment by VestryOd** [comment]
image
And no sign in with login `loginov_rocks `& password: `TEST_PASSWORD`. If I have to use another input data - please send me valid.

**Comment by loginov-rocks** [comment]
Hi @VestryOd

Yes, there were no requirements to implement Cognito auth in the front end app, so I understand why you faced such issues :)

1. **Product Service** which is serving API /products requires Cognito auth, as per requirements, let's call it "user auth".
But apart from that, you can obtain the token by clicking on the lock button as in the examples and Sign In there - try it, it's fully working. After you log in with **your credentials** (it is not related to the loginov_rocks:TEST_PASSWORD), you will be redirected to the front-end application which will show you all /products without unauthorized issues.
2. **Import Service** which is serving API /import requires Basic auth, as per requirements, let's call it "admin auth". API /import used on the admin page where you try to upload test.csv. Of course you can trigger it directly: API: https://78s203i22m.execute-api.eu-central-1.amazonaws.com/dev/import?name=test.csv - and this one requires loginov_rocks:TEST_PASSWORD creds.

**Comment by loginov-rocks** [comment]
Hi @DzmitryU

Please recheck or contact me on Skype "danilaloginov" if still not working, I can't find your contacts other than github name :)

On the screenshots, the first /import is done without the token, returns 403, now with CORS. The second /import is with the `authorization_token`, works:

Screen Shot 2020-12-03 at 6 58 09 PM
Screen Shot 2020-12-03 at 6 58 15 PM

**Comment by loginov-rocks** [comment]
@VestryOd @DzmitryU guys, this one still needs your attention, please :)

**Comment by loginov-rocks** [comment]
@VestryOd @DzmitryU guys? :)

**Pull request merged**
